version: "3.9"

services:
  trading_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading_bot
    restart: always
    environment:
      - SEQ_LEN=${SEQ_LEN}
      - BATCH_SIZE=${BATCH_SIZE}
      - EPOCHS=${EPOCHS}
      - MODEL_SAVE_PATH=${MODEL_SAVE_PATH}
      - DATA_SAVE_PATH=${DATA_SAVE_PATH}
      - TRAINING_DATA_JSON=${TRAINING_DATA_JSON}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - BUY_THRESHOLD=${BUY_THRESHOLD}
      - SELL_THRESHOLD=${SELL_THRESHOLD}
      - TRADE_AMOUNT=${TRADE_AMOUNT}
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    entrypoint: ["sh", "-c", "python main.py"]
    tty: true